title: "Neha Umathe Balwaik"
description: "Master's in Data Science | Stevens Institute of Technology | Data Analytics Engineer | Passionate about Machine Learning, Data Visualization, and Statistical Analysis."
theme: jekyll-theme-cayman
